package org.anasoid.impexia.core;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Assert;
import org.junit.Test;

public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();
    Assert.assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
