package org.anasoid.impexia.core;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */



public class LibraryTest {
  @Test
  public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();
    Assertions.assertTrue(classUnderTest.someLibraryMethod(),
        "someLibraryMethod should return 'true'");
  }
}
