package codecontrol


/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    checkstyle
}


checkstyle {

    configFile = rootProject.file("config/checkstyle/google_checks.xml")
    toolVersion = "11.0.0"
    maxErrors = 0
    maxWarnings = 0

}

tasks.withType<Checkstyle>().configureEach {
    ignoreFailures = false;

}