package codecontrol

import org.gradle.kotlin.dsl.java
import org.gradle.kotlin.dsl.pmd

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    pmd
}
pmd {
    toolVersion = "7.16.0"
    isConsoleOutput = true
    sourceSets = listOf(java.sourceSets.findByName("main"))
    ruleSetFiles = files("${rootProject.projectDir}/config/pmd/pmd.xml")
    ruleSets = listOf()
}