package codecontrol


/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    jacoco
}

// Do not generate reports for individual projects
tasks.jacocoTestReport {
    enabled = true
}

jacoco {
    toolVersion = "0.8.12"
}

tasks.withType<JacocoCoverageVerification> {
    violationRules {
        rule {
            limit {
                minimum = BigDecimal(0.62)
            }
        }
    }

    afterEvaluate {
        classDirectories.setFrom(
                files(
                        classDirectories.files.map {
                            fileTree(it).apply {
                                exclude(listOf("com/opencsv/**", "org/anasoid/impexia/csv/opencsv/**", "**/generated/**"))
                            }
                        }
                )
        )
    }
}

tasks.withType<JacocoReport> {
    afterEvaluate {
        classDirectories.setFrom(
                files(
                        classDirectories.files.map {
                            fileTree(it).apply {
                                exclude(listOf("com/opencsv/**", "org/anasoid/impexia/csv/opencsv/**", "**/generated/**"))
                            }
                        }
                )
        )
    }
}
