package codecontrol

import gradle.kotlin.dsl.accessors._53fcf84b5c55ae3c098e3bb78b94da8d.jacoco
import gradle.kotlin.dsl.accessors._53fcf84b5c55ae3c098e3bb78b94da8d.jacocoTestReport
import org.gradle.kotlin.dsl.jacoco
import org.gradle.kotlin.dsl.java

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    jacoco
}

// Do not generate reports for individual projects
tasks.jacocoTestReport {
    enabled = true
}

jacoco {
    toolVersion = "0.8.12"
}

tasks.withType<JacocoCoverageVerification> {
    violationRules {
        rule {
            limit {
                minimum = BigDecimal(0.62)
            }
        }
    }

    afterEvaluate {
        classDirectories.setFrom(
            files(
                classDirectories.files.map {
                    fileTree(it).apply {
                        exclude("**/generated/**")
                    }
                }
            )
        )
    }
}

tasks.withType<JacocoReport> {
    afterEvaluate {
        classDirectories.setFrom(
            files(
                classDirectories.files.map {
                    fileTree(it).apply {
                        exclude("**/generated/**")
                    }
                }
            )
        )
    }
}
