package codecontrol

import gradle.kotlin.dsl.accessors._b5258395f318e256771440d90b569284.java
import gradle.kotlin.dsl.accessors._b5258395f318e256771440d90b569284.pmd
import org.gradle.kotlin.dsl.java
import org.gradle.kotlin.dsl.pmd

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    pmd
}
pmd {
    toolVersion = "7.8.0"
    isConsoleOutput = true
    sourceSets = listOf(java.sourceSets.findByName("main"))
    ruleSetFiles = files("${rootProject.projectDir}/config/pmd/pmd.xml")
    ruleSets = listOf()
}