language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: anasoid
    token:
      secure: haI9AG5gQMl77DYNFhBZrOptTX1viKdnEvupDKR3aBhaDiGkBe1VM5+JoR97Q3PSL+w7yMW8MXY41UgviwlMPCUFAzZ6BSIGMVE/tOCs9C+ut2eBV/c2SUKNlwXd+OTPEQthdWSaXH2qHJ5A5PdyXTDKMt5RNIUhAgouEzmHbzbYJQ8xgD1VmeSv0IoMIAwPwOSel49M77g+bAWLMkz40nhEb7xkqUkeeFOQOj9Kf5Hz8YfsLePTJFu8cpdao7/1jjTAeIdkkYh8Vm3JJmujWU+EXNaoKHCg2FlvNRpyv4vgZoDA5KJMpztSMcn56hugRySg8lJLUtVxur3D8+3vOH1HYX86fF02KaaJux12CSjiLO2qG1lx2rRGrqYGZeSIwRoohoI2WmIFSvHd/NbZ3J1A8D4u4+/Z1uhaUwZpBPLqYGp1cbRVGNpN55yeaLq4h8QdtgnP5Z6JgFsqvVQ81jSzFSg4Pw0rYXJZRTI0FTdTpwhE3QlVqS6Aa/799alexfQOy7zUFjyJiALr1Kmd1poGVkn6SIV4MN9eHlPYAVdjuPJkfjfOJwZSALsp0D70c36GZ+NA340KFzbhOE7QgSS65JpXfFIb2p6WXi599882pRlYTjkuUGcr+1R7lS+e+31dkIoQ+a+TURArX2fZUXIEBQqgUIMMoOP+LEPCqLM=

jdk:
- oraclejdk8
script:
- "./gradlew sonarqube"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
