/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":impexia-meta"))
    implementation(project(":impexia-core"))
}
