/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":impexia-exporting"))
    implementation(project(":impexia-importing"))
}
