/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":impexia-meta"))
    implementation(project(":impexia-core"))
    implementation(project(":impexia-exporting"))
    implementation(project(":impexia-importing"))
    implementation(libs.opencsv)
    compileOnly(libs.hibernate.core)
    compileOnly(libs.jakarta.persistence.api)

    testImplementation(project(":impexia-test-app"))
    testImplementation(libs.hibernate.core)
    testImplementation(libs.jakarta.persistence.api)
    testRuntimeOnly(libs.hsqldb)

}
