/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
    id("io.freefair.lombok")
    id("codecontrol.buildlogic.jacoco-conventions")
    id("codecontrol.buildlogic.pmd-conventions")
    id("codecontrol.buildlogic.spotless-conventions")
    id("codecontrol.buildlogic.checkstyle-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.14.0")
    }

    // SLF4J as a facade over Log4j2 required dependencies
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.25.2")
    // Bridges from other logging implementations to SLF4J. Be careful not to bridge SLF4J itself to
    implementation("org.slf4j:slf4j-api:2.0.17")

    //Apache common

    implementation("org.apache.commons:commons-lang3:3.19.0")
    implementation("org.apache.commons:commons-collections4:4.5.0")
    testImplementation("commons-io:commons-io:2.20.0")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:6.0.1")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    // https://mvnrepository.com/artifact/org.assertj/assertj-core
    testImplementation("org.assertj:assertj-core:3.27.6")

}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
