/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
    id("io.freefair.lombok")
    id("buildlogic.jacoco-conventions")
    id("buildlogic.pmd-conventions")
    id("buildlogic.checkstyle-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    constraints {
        // Define dependency versions as constraints
        implementation("org.apache.commons:commons-text:1.13.0")
    }

    // SLF4J as a facade over Log4j2 required dependencies
    implementation("org.apache.logging.log4j:log4j-api:2.24.3")
    implementation("org.apache.logging.log4j:log4j-core:2.24.3")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.24.3")
    // Bridges from other logging implementations to SLF4J. Be careful not to bridge SLF4J itself to
    implementation("org.slf4j:jul-to-slf4j:2.0.16")
    implementation("org.slf4j:jcl-over-slf4j:2.0.16")
    implementation("org.slf4j:log4j-over-slf4j:2.0.16")

    //Apache common

    implementation("org.apache.commons:commons-lang3:3.17.0")
    testImplementation("commons-io:commons-io:2.18.0")

    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
