/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    pmd
}
pmd {
    toolVersion = "7.8.0"
    isConsoleOutput = true
    sourceSets = listOf(java.sourceSets.findByName("main"))
    ruleSetFiles = files("${rootProject.projectDir}/config/pmd/pmd.xml")
    ruleSets = listOf()
}