/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(libs.jakarta.persistence.api)
    //Test
    testRuntimeOnly(libs.hibernate.core)
    testRuntimeOnly("org.hsqldb:hsqldb:2.7.4")
}
