# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name : Java CI with Gradle

on : [ push, pull_request ]

jobs :
  build :

    runs-on : ubuntu-latest

    steps :
      - name : Checkout
        uses : actions/checkout@v4

      - name : Set up JDK 17
        uses : actions/setup-java@v4
        with :
          java-version : 17
          distribution : 'temurin'

      - name : Cache Sonar
        uses : actions/cache@v4
        with :
          path : |
            ~/.sonar
          key : ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle*') }}
          restore-keys : |
            ${{ runner.os }}-sonar-

      - name : Setup Gradle
        uses : gradle/actions/setup-gradle@v4
        with :
          build-scan-publish : true
          build-scan-terms-of-use-url : "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree : "yes"

      - name : Build with Gradle
        run : ./gradlew build


      - name : Publish Test Report
        uses : mikepenz/action-junit-report@v5
        with :
          report_paths : '**/build/test-results/test/TEST-*.xml'
          github_token : ${{ secrets.GITHUB_TOKEN }}

      - name : Upload artifact Report
        uses : actions/upload-artifact@v4
        with :
          name : reports
          path : '**/build/reports/**'

      - name : Run codacy-coverage-reporter
        uses : codacy/codacy-coverage-reporter-action@v1.3.0
        with :
          project-token : ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports : ${{ github.workspace }}/buildUtils/code-coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml

      - name : CodeCov
        uses : codecov/codecov-action@v5
        with :
          token : ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files : ${{ github.workspace }}/buildUtils/code-coverage-report/build/reports/jacoco/testCodeCoverageReport/testCodeCoverageReport.xml # optional
          verbose : true

      - name : Sonar check
        run : ./gradlew sonar
        env :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN : ${{ secrets.SONAR_TOKEN }}
